### ISSUE TITLE
Fehler, bitte ändern :D

### ISSUE THREAD

**Issue by Quoboo** [WonderBuildEU/Citybuild#1]
wc zu Coins, Statt jedem Spieler aufgelistet bei /payall : Du hast jedem Spieler <coins> Coins gegeben.

**Comment by LUPLUV** [comment]
Danke für deinen Verbesserungsvorschlag, wir haben den Vorschlag umgesetzt.

**Comment by LUPLUV** [comment]
Danke für deinen Verbesserungsvorschlag, wir haben den Vorschlag umgesetzt.
