### ISSUE TITLE
Kotlin?

### ISSUE THREAD

**Issue by CoasterFreakDE** [WonderBuildEU/Citybuild#19]
Eventuell auf Kotlin upgraden?

https://kotlinlang.org/

**Comment by CoasterFreakDE** [comment]
[Kotlin Präsentation Bewerbertag.pptx](https://github.com/WonderBuildEU/Citybuild/files/10316680/Kotlin.Prasentation.Bewerbertag.pptx)

**Comment by CoasterFreakDE** [comment]
Standard Libs sind bereits im Projekt enthalten

**Comment by LUPLUV** [comment]
hab kein pp
