### ISSUE TITLE
Tablist Teamspeak entfernen

### ISSUE THREAD

**Issue by Quoboo** [WonderBuildEU/Citybuild#30]
In der Tab TS entfernen. Anschließend den Shop dann über Discord. Das es wieder schön ist. 
Und shop.wonderbuild.net auf store.wonderbuild.net ändern. 

Lg

**Comment by CoasterFreakDE** [comment]
Muss per Config von TAB geändert werden

**Comment by LUPLUV** [comment]
Danke für deinen Verbesserungsvorschlag, wir haben den Vorschlag umgesetzt.
