### ISSUE TITLE
Effekte GUI

### ISSUE THREAD

**Issue by Quoboo** [WonderBuildEU/Citybuild#31]
Den Monster Effekt auf Zauber Effekt umändern. Und Redstone Effekt auf Magma Effekt umändern.

**Comment by CoasterFreakDE** [comment]
![image](https://user-images.githubusercontent.com/28011628/210012508-d65e78e0-1791-41f8-b67f-8d7e86c09c61.png)

Beim Auswahl-Text fehlt der Change noch
