### ISSUE TITLE
Owner permission um jeden zu bannen kicken startkick usw.

### ISSUE THREAD

**Issue by Quoboo** [WonderBuildEU/Citybuild#50]
Keiner soll Rechte haben den Owner Rang kicken bannen usw zu dürfen.

Keine Ahnung wie aber das muss. xD

LG

**Comment by CoasterFreakDE** [comment]
Eventuell bei all denen per Perm System mit den Gewichtungen arbeiten?
Sodass man immer nur niedrigere Ränge kicken, bannen usw. kann

**Comment by Quoboo** [comment]
Yes

**Comment by LUPLUV** [comment]
nö

**Comment by LUPLUV** [comment]
Danke für deinen Vorschlag, jedoch haben wir uns dazu entschlossen diesen nicht umzusetzen.
