### ISSUE TITLE
Ban Rechte

### ISSUE THREAD

**Issue by Quoboo** [WonderBuildEU/Citybuild#6]
Owner soll Rechte bekommen um jeden zu bannen.
Untere Ränge dürfen keine Berechtigung haben den Owner zu bannen.

Generell untere Ränge dürfen höhere Ränge nicht bannen? Oder?

**Comment by LUPLUV** [comment]
Danke für deinen Vorschlag, jedoch haben wir uns dazu entschlossen diesen nicht umzusetzen.
