### ISSUE TITLE
Tablist store neben discord sieht nicht gut aus

### ISSUE THREAD

**Issue by LUPLUV** [WonderBuildEU/Citybuild#62]
![image](https://user-images.githubusercontent.com/75487485/210157365-6bf1d1db-b0b6-402a-b1ee-3eda22693021.png)

**Comment by Quoboo** [comment]
Ja hast du recht, sieht nicht gut aus. Mach es am besten wieder übereinander.
Lg

**Comment by LUPLUV** [comment]
Danke für deinen Verbesserungsvorschlag, wir haben den Vorschlag umgesetzt.
