### ISSUE TITLE
Zeile Frei, Chat

### ISSUE THREAD

**Issue by Quoboo** [WonderBuildEU/Citybuild#9]
Des öfteren buggt das mit der Nachricht wo oben und unten noch eine Zeile frei ist sehr.
Manchmal sind oben 2 Zeilen frei und unten keine oder anders rum. Manchmal kommen die auch viel zu spät.

Lg

**Comment by CoasterFreakDE** [comment]
Man kann das Ansich jetzt ausschalten mit `/togglebigchat` ( #16 )

Das buggen wird man nicht beheben können, da es an MC liegt.

**Comment by Quoboo** [comment]
Ich würde den Command: /togglefreiezeile bevorzugen ^^. @CoasterFreakDE
